<?php
/**
 * ClientApi
 * PHP version 7.2
 *
 * @category Class
 * @package  KeyStackApp\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Firekeys-stage.com
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace KeyStackApp\Client\Api;

use GuzzleHttp\Psr7\MultipartStream;
use Http\Client\Common\Plugin\ErrorPlugin;
use Http\Client\Common\Plugin\RedirectPlugin;
use Http\Client\Common\PluginClient;
use Http\Client\Common\PluginClientFactory;
use Http\Client\Exception\HttpException;
use Http\Client\HttpAsyncClient;
use Http\Discovery\HttpAsyncClientDiscovery;
use Http\Discovery\Psr17FactoryDiscovery;
use Http\Discovery\Psr18ClientDiscovery;
use Http\Message\RequestFactory;
use Http\Promise\Promise;
use KeyStackApp\Client\ApiException;
use KeyStackApp\Client\Configuration;
use KeyStackApp\Client\DebugPlugin;
use KeyStackApp\Client\HeaderSelector;
use KeyStackApp\Client\FormDataProcessor;
use KeyStackApp\Client\ObjectSerializer;
use Psr\Http\Client\ClientExceptionInterface;
use Psr\Http\Client\ClientInterface;
use Psr\Http\Message\RequestFactoryInterface;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use Psr\Http\Message\StreamFactoryInterface;
use Psr\Http\Message\UriFactoryInterface;
use Psr\Http\Message\UriInterface;
use function sprintf;

/**
 * ClientApi Class Doc Comment
 *
 * @category Class
 * @package  KeyStackApp\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ClientApi
{
    /**
     * @var PluginClient
     */
    protected $httpClient;

    /**
     * @var PluginClient
     */
    protected $httpAsyncClient;

    /**
     * @var UriFactoryInterface
     */
    protected $uriFactory;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /**
     * @var RequestFactoryInterface
     */
    protected $requestFactory;

    /**
     * @var StreamFactoryInterface
     */
    protected $streamFactory;

    public function __construct(
        ?ClientInterface $httpClient = null,
        ?Configuration $config = null,
        ?HttpAsyncClient $httpAsyncClient = null,
        ?UriFactoryInterface $uriFactory = null,
        ?RequestFactoryInterface $requestFactory = null,
        ?StreamFactoryInterface $streamFactory = null,
        ?HeaderSelector $selector = null,
        ?array $plugins = null,
        $hostIndex = 0
    ) {
        $this->config = $config ?? (new Configuration())->setHost('http://localhost');
        $this->requestFactory = $requestFactory ?? Psr17FactoryDiscovery::findRequestFactory();
        $this->streamFactory = $streamFactory ?? Psr17FactoryDiscovery::findStreamFactory();

        $plugins = $plugins ?? [
            new RedirectPlugin(['strict' => true]),
            new ErrorPlugin(),
        ];

        if ($this->config->getDebug()) {
            $plugins[] = new DebugPlugin(fopen($this->config->getDebugFile(), 'ab'));
        }

        $this->httpClient = (new PluginClientFactory())->createClient(
            $httpClient ?? Psr18ClientDiscovery::find(),
            $plugins
        );

        $this->httpAsyncClient = (new PluginClientFactory())->createClient(
            $httpAsyncClient ?? HttpAsyncClientDiscovery::find(),
            $plugins
        );

        $this->uriFactory = $uriFactory ?? Psr17FactoryDiscovery::findUriFactory();

        $this->headerSelector = $selector ?? new HeaderSelector();

        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation activateLicense
     *
     * @param  \KeyStackApp\Client\Model\ActivateLicense $activateLicense activateLicense (optional)
     *
     * @throws \KeyStackApp\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \KeyStackApp\Client\Model\ActivationResponse|\KeyStackApp\Client\Model\ValidateLicense401Response|\KeyStackApp\Client\Model\ValidateLicense404Response|\KeyStackApp\Client\Model\ValidateLicense423Response
     */
    public function activateLicense($activateLicense = null)
    {
        list($response) = $this->activateLicenseWithHttpInfo($activateLicense);
        return $response;
    }

    /**
     * Operation activateLicenseWithHttpInfo
     *
     * @param  \KeyStackApp\Client\Model\ActivateLicense $activateLicense (optional)
     *
     * @throws \KeyStackApp\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \KeyStackApp\Client\Model\ActivationResponse|\KeyStackApp\Client\Model\ValidateLicense401Response|\KeyStackApp\Client\Model\ValidateLicense404Response|\KeyStackApp\Client\Model\ValidateLicense423Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function activateLicenseWithHttpInfo($activateLicense = null)
    {
        $request = $this->activateLicenseRequest($activateLicense);

        try {
            try {
                $response = $this->httpClient->sendRequest($request);
            } catch (HttpException $e) {
                $response = $e->getResponse();
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $response->getStatusCode(),
                        (string) $request->getUri()
                    ),
                    $request,
                    $response,
                    $e
                );
            } catch (ClientExceptionInterface $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $request,
                    null,
                    $e
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\KeyStackApp\Client\Model\ActivationResponse',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\KeyStackApp\Client\Model\ValidateLicense401Response',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\KeyStackApp\Client\Model\ValidateLicense404Response',
                        $request,
                        $response,
                    );
                case 423:
                    return $this->handleResponseWithDataType(
                        '\KeyStackApp\Client\Model\ValidateLicense423Response',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $request,
                    $response
                );
            }

            return $this->handleResponseWithDataType(
                '\KeyStackApp\Client\Model\ActivationResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KeyStackApp\Client\Model\ActivationResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KeyStackApp\Client\Model\ValidateLicense401Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KeyStackApp\Client\Model\ValidateLicense404Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 423:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KeyStackApp\Client\Model\ValidateLicense423Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation activateLicenseAsync
     *
     * @param  \KeyStackApp\Client\Model\ActivateLicense $activateLicense (optional)
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function activateLicenseAsync($activateLicense = null)
    {
        return $this->activateLicenseAsyncWithHttpInfo($activateLicense)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation activateLicenseAsyncWithHttpInfo
     *
     * @param  \KeyStackApp\Client\Model\ActivateLicense $activateLicense (optional)
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function activateLicenseAsyncWithHttpInfo($activateLicense = null)
    {
        $returnType = '\KeyStackApp\Client\Model\ActivationResponse';
        $request = $this->activateLicenseRequest($activateLicense);

        return $this->httpAsyncClient->sendAsyncRequest($request)
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function (HttpException $exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $exception->getRequest(),
                        $exception->getResponse(),
                        $exception
                    );
                }
            );
    }

    /**
     * Create request for operation 'activateLicense'
     *
     * @param  \KeyStackApp\Client\Model\ActivateLicense $activateLicense (optional)
     *
     * @throws \InvalidArgumentException
     * @return RequestInterface
     */
    public function activateLicenseRequest($activateLicense = null)
    {

        $resourcePath = '/v1/licenses/activate';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = null;
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            'application/json',
            $multipart
        );

        // for model (json/xml)
        if (isset($activateLicense)) {
            if ($this->headerSelector->isJsonMime($headers['Content-Type'])) {
                $httpBody = json_encode(ObjectSerializer::sanitizeForSerialization($activateLicense));
            } else {
                $httpBody = $activateLicense;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($this->headerSelector->isJsonMime($headers['Content-Type'])) {
                $httpBody = json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer (JWT) authentication (access token)
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();

        $uri = $this->createUri($operationHost, $resourcePath, $queryParams);

        return $this->createRequest('POST', $uri, $headers, $httpBody);
    }

    /**
     * Operation deactivateLicense
     *
     * @param  \KeyStackApp\Client\Model\DeactivateLicenseInput $deactivateLicenseInput The input parameters. (required)
     *
     * @throws \KeyStackApp\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \KeyStackApp\Client\Model\DeactivationResponse|\KeyStackApp\Client\Model\ValidateLicense401Response|\KeyStackApp\Client\Model\ValidateLicense404Response|\KeyStackApp\Client\Model\ValidateLicense423Response
     */
    public function deactivateLicense($deactivateLicenseInput)
    {
        list($response) = $this->deactivateLicenseWithHttpInfo($deactivateLicenseInput);
        return $response;
    }

    /**
     * Operation deactivateLicenseWithHttpInfo
     *
     * @param  \KeyStackApp\Client\Model\DeactivateLicenseInput $deactivateLicenseInput The input parameters. (required)
     *
     * @throws \KeyStackApp\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \KeyStackApp\Client\Model\DeactivationResponse|\KeyStackApp\Client\Model\ValidateLicense401Response|\KeyStackApp\Client\Model\ValidateLicense404Response|\KeyStackApp\Client\Model\ValidateLicense423Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function deactivateLicenseWithHttpInfo($deactivateLicenseInput)
    {
        $request = $this->deactivateLicenseRequest($deactivateLicenseInput);

        try {
            try {
                $response = $this->httpClient->sendRequest($request);
            } catch (HttpException $e) {
                $response = $e->getResponse();
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $response->getStatusCode(),
                        (string) $request->getUri()
                    ),
                    $request,
                    $response,
                    $e
                );
            } catch (ClientExceptionInterface $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $request,
                    null,
                    $e
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\KeyStackApp\Client\Model\DeactivationResponse',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\KeyStackApp\Client\Model\ValidateLicense401Response',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\KeyStackApp\Client\Model\ValidateLicense404Response',
                        $request,
                        $response,
                    );
                case 423:
                    return $this->handleResponseWithDataType(
                        '\KeyStackApp\Client\Model\ValidateLicense423Response',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $request,
                    $response
                );
            }

            return $this->handleResponseWithDataType(
                '\KeyStackApp\Client\Model\DeactivationResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KeyStackApp\Client\Model\DeactivationResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KeyStackApp\Client\Model\ValidateLicense401Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KeyStackApp\Client\Model\ValidateLicense404Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 423:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KeyStackApp\Client\Model\ValidateLicense423Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation deactivateLicenseAsync
     *
     * @param  \KeyStackApp\Client\Model\DeactivateLicenseInput $deactivateLicenseInput The input parameters. (required)
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function deactivateLicenseAsync($deactivateLicenseInput)
    {
        return $this->deactivateLicenseAsyncWithHttpInfo($deactivateLicenseInput)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation deactivateLicenseAsyncWithHttpInfo
     *
     * @param  \KeyStackApp\Client\Model\DeactivateLicenseInput $deactivateLicenseInput The input parameters. (required)
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function deactivateLicenseAsyncWithHttpInfo($deactivateLicenseInput)
    {
        $returnType = '\KeyStackApp\Client\Model\DeactivationResponse';
        $request = $this->deactivateLicenseRequest($deactivateLicenseInput);

        return $this->httpAsyncClient->sendAsyncRequest($request)
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function (HttpException $exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $exception->getRequest(),
                        $exception->getResponse(),
                        $exception
                    );
                }
            );
    }

    /**
     * Create request for operation 'deactivateLicense'
     *
     * @param  \KeyStackApp\Client\Model\DeactivateLicenseInput $deactivateLicenseInput The input parameters. (required)
     *
     * @throws \InvalidArgumentException
     * @return RequestInterface
     */
    public function deactivateLicenseRequest($deactivateLicenseInput)
    {
        // verify the required parameter 'deactivateLicenseInput' is set
        if ($deactivateLicenseInput === null || (is_array($deactivateLicenseInput) && count($deactivateLicenseInput) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $deactivateLicenseInput when calling deactivateLicense'
            );
        }

        $resourcePath = '/v1/licenses/deactivate';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = null;
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            'application/json',
            $multipart
        );

        // for model (json/xml)
        if (isset($deactivateLicenseInput)) {
            if ($this->headerSelector->isJsonMime($headers['Content-Type'])) {
                $httpBody = json_encode(ObjectSerializer::sanitizeForSerialization($deactivateLicenseInput));
            } else {
                $httpBody = $deactivateLicenseInput;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($this->headerSelector->isJsonMime($headers['Content-Type'])) {
                $httpBody = json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer (JWT) authentication (access token)
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();

        $uri = $this->createUri($operationHost, $resourcePath, $queryParams);

        return $this->createRequest('POST', $uri, $headers, $httpBody);
    }

    /**
     * Operation login
     *
     * @param  \KeyStackApp\Client\Model\LoginInput $loginInput The input parameters for the login endpoint. (required)
     *
     * @throws \KeyStackApp\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \KeyStackApp\Client\Model\LoginOutput|\KeyStackApp\Client\Model\ValidateLicense401Response
     */
    public function login($loginInput)
    {
        list($response) = $this->loginWithHttpInfo($loginInput);
        return $response;
    }

    /**
     * Operation loginWithHttpInfo
     *
     * @param  \KeyStackApp\Client\Model\LoginInput $loginInput The input parameters for the login endpoint. (required)
     *
     * @throws \KeyStackApp\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \KeyStackApp\Client\Model\LoginOutput|\KeyStackApp\Client\Model\ValidateLicense401Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function loginWithHttpInfo($loginInput)
    {
        $request = $this->loginRequest($loginInput);

        try {
            try {
                $response = $this->httpClient->sendRequest($request);
            } catch (HttpException $e) {
                $response = $e->getResponse();
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $response->getStatusCode(),
                        (string) $request->getUri()
                    ),
                    $request,
                    $response,
                    $e
                );
            } catch (ClientExceptionInterface $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $request,
                    null,
                    $e
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\KeyStackApp\Client\Model\LoginOutput',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\KeyStackApp\Client\Model\ValidateLicense401Response',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $request,
                    $response
                );
            }

            return $this->handleResponseWithDataType(
                '\KeyStackApp\Client\Model\LoginOutput',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KeyStackApp\Client\Model\LoginOutput',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KeyStackApp\Client\Model\ValidateLicense401Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation loginAsync
     *
     * @param  \KeyStackApp\Client\Model\LoginInput $loginInput The input parameters for the login endpoint. (required)
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function loginAsync($loginInput)
    {
        return $this->loginAsyncWithHttpInfo($loginInput)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation loginAsyncWithHttpInfo
     *
     * @param  \KeyStackApp\Client\Model\LoginInput $loginInput The input parameters for the login endpoint. (required)
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function loginAsyncWithHttpInfo($loginInput)
    {
        $returnType = '\KeyStackApp\Client\Model\LoginOutput';
        $request = $this->loginRequest($loginInput);

        return $this->httpAsyncClient->sendAsyncRequest($request)
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function (HttpException $exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $exception->getRequest(),
                        $exception->getResponse(),
                        $exception
                    );
                }
            );
    }

    /**
     * Create request for operation 'login'
     *
     * @param  \KeyStackApp\Client\Model\LoginInput $loginInput The input parameters for the login endpoint. (required)
     *
     * @throws \InvalidArgumentException
     * @return RequestInterface
     */
    public function loginRequest($loginInput)
    {
        // verify the required parameter 'loginInput' is set
        if ($loginInput === null || (is_array($loginInput) && count($loginInput) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $loginInput when calling login'
            );
        }

        $resourcePath = '/v1/login';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = null;
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            'input',
            $multipart
        );

        // for model (json/xml)
        if (isset($loginInput)) {
            if ($this->headerSelector->isJsonMime($headers['Content-Type'])) {
                $httpBody = json_encode(ObjectSerializer::sanitizeForSerialization($loginInput));
            } else {
                $httpBody = $loginInput;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($this->headerSelector->isJsonMime($headers['Content-Type'])) {
                $httpBody = json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();

        $uri = $this->createUri($operationHost, $resourcePath, $queryParams);

        return $this->createRequest('POST', $uri, $headers, $httpBody);
    }

    /**
     * Operation manifestPublicRead
     *
     * @param  string $cacheKey cacheKey (required)
     *
     * @throws \KeyStackApp\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return object|\KeyStackApp\Client\Model\ValidateLicense401Response|\KeyStackApp\Client\Model\ValidateLicense404Response|\KeyStackApp\Client\Model\ValidateLicense423Response
     */
    public function manifestPublicRead($cacheKey)
    {
        list($response) = $this->manifestPublicReadWithHttpInfo($cacheKey);
        return $response;
    }

    /**
     * Operation manifestPublicReadWithHttpInfo
     *
     * @param  string $cacheKey (required)
     *
     * @throws \KeyStackApp\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of object|\KeyStackApp\Client\Model\ValidateLicense401Response|\KeyStackApp\Client\Model\ValidateLicense404Response|\KeyStackApp\Client\Model\ValidateLicense423Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function manifestPublicReadWithHttpInfo($cacheKey)
    {
        $request = $this->manifestPublicReadRequest($cacheKey);

        try {
            try {
                $response = $this->httpClient->sendRequest($request);
            } catch (HttpException $e) {
                $response = $e->getResponse();
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $response->getStatusCode(),
                        (string) $request->getUri()
                    ),
                    $request,
                    $response,
                    $e
                );
            } catch (ClientExceptionInterface $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $request,
                    null,
                    $e
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        'object',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\KeyStackApp\Client\Model\ValidateLicense401Response',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\KeyStackApp\Client\Model\ValidateLicense404Response',
                        $request,
                        $response,
                    );
                case 423:
                    return $this->handleResponseWithDataType(
                        '\KeyStackApp\Client\Model\ValidateLicense423Response',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $request,
                    $response
                );
            }

            return $this->handleResponseWithDataType(
                'object',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        'object',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KeyStackApp\Client\Model\ValidateLicense401Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KeyStackApp\Client\Model\ValidateLicense404Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 423:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KeyStackApp\Client\Model\ValidateLicense423Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation manifestPublicReadAsync
     *
     * @param  string $cacheKey (required)
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function manifestPublicReadAsync($cacheKey)
    {
        return $this->manifestPublicReadAsyncWithHttpInfo($cacheKey)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation manifestPublicReadAsyncWithHttpInfo
     *
     * @param  string $cacheKey (required)
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function manifestPublicReadAsyncWithHttpInfo($cacheKey)
    {
        $returnType = 'object';
        $request = $this->manifestPublicReadRequest($cacheKey);

        return $this->httpAsyncClient->sendAsyncRequest($request)
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function (HttpException $exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $exception->getRequest(),
                        $exception->getResponse(),
                        $exception
                    );
                }
            );
    }

    /**
     * Create request for operation 'manifestPublicRead'
     *
     * @param  string $cacheKey (required)
     *
     * @throws \InvalidArgumentException
     * @return RequestInterface
     */
    public function manifestPublicReadRequest($cacheKey)
    {
        // verify the required parameter 'cacheKey' is set
        if ($cacheKey === null || (is_array($cacheKey) && count($cacheKey) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $cacheKey when calling manifestPublicRead'
            );
        }
        if (strlen($cacheKey) < 3) {
            throw new \InvalidArgumentException('invalid length for "$cacheKey" when calling ClientApi.manifestPublicRead, must be bigger than or equal to 3.');
        }


        $resourcePath = '/v1/manifest/public-read/{cacheKey}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = null;
        $multipart = false;



        // path params
        if ($cacheKey !== null) {
            $resourcePath = str_replace(
                '{' . 'cacheKey' . '}',
                ObjectSerializer::toPathValue($cacheKey),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            '',
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($this->headerSelector->isJsonMime($headers['Content-Type'])) {
                $httpBody = json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();

        $uri = $this->createUri($operationHost, $resourcePath, $queryParams);

        return $this->createRequest('GET', $uri, $headers, $httpBody);
    }

    /**
     * Operation validateLicense
     *
     * @param  \KeyStackApp\Client\Model\ValidateLicenseRequest $validateLicenseRequest validateLicenseRequest (optional)
     *
     * @throws \KeyStackApp\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \KeyStackApp\Client\Model\LicenseKey|\KeyStackApp\Client\Model\ValidateLicense401Response|\KeyStackApp\Client\Model\ValidateLicense404Response|\KeyStackApp\Client\Model\ValidateLicense423Response
     */
    public function validateLicense($validateLicenseRequest = null)
    {
        list($response) = $this->validateLicenseWithHttpInfo($validateLicenseRequest);
        return $response;
    }

    /**
     * Operation validateLicenseWithHttpInfo
     *
     * @param  \KeyStackApp\Client\Model\ValidateLicenseRequest $validateLicenseRequest (optional)
     *
     * @throws \KeyStackApp\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \KeyStackApp\Client\Model\LicenseKey|\KeyStackApp\Client\Model\ValidateLicense401Response|\KeyStackApp\Client\Model\ValidateLicense404Response|\KeyStackApp\Client\Model\ValidateLicense423Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function validateLicenseWithHttpInfo($validateLicenseRequest = null)
    {
        $request = $this->validateLicenseRequest($validateLicenseRequest);

        try {
            try {
                $response = $this->httpClient->sendRequest($request);
            } catch (HttpException $e) {
                $response = $e->getResponse();
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $response->getStatusCode(),
                        (string) $request->getUri()
                    ),
                    $request,
                    $response,
                    $e
                );
            } catch (ClientExceptionInterface $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $request,
                    null,
                    $e
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\KeyStackApp\Client\Model\LicenseKey',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\KeyStackApp\Client\Model\ValidateLicense401Response',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\KeyStackApp\Client\Model\ValidateLicense404Response',
                        $request,
                        $response,
                    );
                case 423:
                    return $this->handleResponseWithDataType(
                        '\KeyStackApp\Client\Model\ValidateLicense423Response',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $request,
                    $response
                );
            }

            return $this->handleResponseWithDataType(
                '\KeyStackApp\Client\Model\LicenseKey',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KeyStackApp\Client\Model\LicenseKey',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KeyStackApp\Client\Model\ValidateLicense401Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KeyStackApp\Client\Model\ValidateLicense404Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 423:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KeyStackApp\Client\Model\ValidateLicense423Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation validateLicenseAsync
     *
     * @param  \KeyStackApp\Client\Model\ValidateLicenseRequest $validateLicenseRequest (optional)
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function validateLicenseAsync($validateLicenseRequest = null)
    {
        return $this->validateLicenseAsyncWithHttpInfo($validateLicenseRequest)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation validateLicenseAsyncWithHttpInfo
     *
     * @param  \KeyStackApp\Client\Model\ValidateLicenseRequest $validateLicenseRequest (optional)
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function validateLicenseAsyncWithHttpInfo($validateLicenseRequest = null)
    {
        $returnType = '\KeyStackApp\Client\Model\LicenseKey';
        $request = $this->validateLicenseRequest($validateLicenseRequest);

        return $this->httpAsyncClient->sendAsyncRequest($request)
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function (HttpException $exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $exception->getRequest(),
                        $exception->getResponse(),
                        $exception
                    );
                }
            );
    }

    /**
     * Create request for operation 'validateLicense'
     *
     * @param  \KeyStackApp\Client\Model\ValidateLicenseRequest $validateLicenseRequest (optional)
     *
     * @throws \InvalidArgumentException
     * @return RequestInterface
     */
    public function validateLicenseRequest($validateLicenseRequest = null)
    {

        $resourcePath = '/v1/licenses/validate';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = null;
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            'application/json',
            $multipart
        );

        // for model (json/xml)
        if (isset($validateLicenseRequest)) {
            if ($this->headerSelector->isJsonMime($headers['Content-Type'])) {
                $httpBody = json_encode(ObjectSerializer::sanitizeForSerialization($validateLicenseRequest));
            } else {
                $httpBody = $validateLicenseRequest;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($this->headerSelector->isJsonMime($headers['Content-Type'])) {
                $httpBody = json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer (JWT) authentication (access token)
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();

        $uri = $this->createUri($operationHost, $resourcePath, $queryParams);

        return $this->createRequest('POST', $uri, $headers, $httpBody);
    }


    /**
     * @param string $method
     * @param string|UriInterface $uri
     * @param array $headers
     * @param string|StreamInterface|null $body
     *
     * @return RequestInterface
     */
    protected function createRequest(string $method, $uri, array $headers = [], $body = null): RequestInterface
    {
        if ($this->requestFactory instanceof RequestFactory) {
            return $this->requestFactory->createRequest(
                $method,
                $uri,
                $headers,
                $body
            );
        }

        if (is_string($body) && '' !== $body && null === $this->streamFactory) {
            throw new \RuntimeException('Cannot create request: A stream factory is required to create a request with a non-empty string body.');
        }

        $request = $this->requestFactory->createRequest($method, $uri);

        foreach ($headers as $key => $value) {
            $request = $request->withHeader($key, $value);
        }

        if (null !== $body && '' !== $body) {
            $request = $request->withBody(
                is_string($body) ? $this->streamFactory->createStream($body) : $body
            );
        }

        return $request;
    }

    private function createUri(
        string $operationHost,
        string $resourcePath,
        array $queryParams
    ): UriInterface {
        $parsedUrl = parse_url($operationHost);

        $host = $parsedUrl['host'] ?? null;
        $scheme = $parsedUrl['scheme'] ?? null;
        $basePath = $parsedUrl['path'] ?? null;
        $port = $parsedUrl['port'] ?? null;
        $user = $parsedUrl['user'] ?? null;
        $password = $parsedUrl['pass'] ?? null;

        $uri = $this->uriFactory->createUri($basePath . $resourcePath)
            ->withHost($host)
            ->withScheme($scheme)
            ->withPort($port)
            ->withQuery(ObjectSerializer::buildQuery($queryParams));

        if ($user) {
            $uri = $uri->withUserInfo($user, $password);
        }

        return $uri;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
			$request,
                        $response,
                        $exception
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
