<?php
/**
 * ClientApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  KeyStack\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Firekeys-stage.com
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace KeyStack\Client\Test\Api;

use \KeyStack\Client\Configuration;
use \KeyStack\Client\ApiException;
use \KeyStack\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ClientApiTest Class Doc Comment
 *
 * @category Class
 * @package  KeyStack\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ClientApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for activateLicense
     *
     * .
     *
     */
    public function testActivateLicense()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deactivateLicense
     *
     * .
     *
     */
    public function testDeactivateLicense()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for manifestPublicRead
     *
     * .
     *
     */
    public function testManifestPublicRead()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for validateLicense
     *
     * .
     *
     */
    public function testValidateLicense()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
